# Generated by Django 5.2 on 2025-04-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("user_tg_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("due_time", models.DateField(null=True)),
                ("category", models.CharField(max_length=50)),
            ],
        ),
    ]
